apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nameOverride }}-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast.ru-7a
  resources:
    requests:
      storage: 50Mi